version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  cache:
    image: redis:latest
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
