---
- name: Advanced Ansible Playbook
  hosts: webservers
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    env_file_path: "{{ playbook_dir }}/.env" 
  roles:
    - role: common
      tags: common
    - role: nginx
      tags: nginx
    - role: php
      when: php_enabled
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
  tasks:
    - name: Check if .env file exists
      stat:
        path: "{{ env_file_path }}"
      register: env_file

    - name: Copy .env file if it doesn't exist
      copy:
        src: "{{ playbook_dir }}/.env.example"
        dest: "{{ env_file_path }}"
      when: not env_file.stat.exists